// Generated by the ftc-construct suite skill (util-audit-dashboard run).
// Adaptation of refract-suite/ftc-shared-foundation/quickstart-template/TeamCode/src/main/java/
// org/firstinspires/ftc/teamcode/RobotConstants.java -- adds one new live-tunable field for the
// intake's velocity PID. Diff against the template file: only the new "-- Intake velocity PID --"
// block below is new; everything else is unchanged from the existing file.
package org.firstinspires.ftc.teamcode;

import com.acmerobotics.dashboard.config.Config;

/**
 * Live-tunable constants, following the FTC Dashboard {@code @Config} idiom
 * carried over from FTCLib-Quickstart's own {@code DriveConstants.java}.
 *
 * IMPORTANT -- read before adding a field here: known-failure-modes.md's
 * "global mutable static state" entry documents a real failure class where a
 * team wrote to a public static field from OpMode/subsystem lifecycle code at
 * runtime. Static fields outlive a single OpMode run (they live on the app
 * process), so a write during run N silently leaks into run N+1 -- and
 * because it only manifests when run N+1 FOLLOWS run N with the wrong prior
 * value, it passes clean in any single tuning run and shows up as "the robot
 * behaved differently in match 2 for no reason." @Config does not protect
 * against this; it only lets the DASHBOARD write these fields between runs.
 *
 * The rule this class exists under: FTC Dashboard may write these fields
 * (that's what @Config is for). OpMode and subsystem code may only READ them.
 * If a value needs to change during a run, make it an instance field on the
 * subsystem that owns it, not a static here.
 */
@Config
public class RobotConstants {

    // -- Shooter (mechanisms/shooter/FlywheelShooter.java) --
    public static double SHOOTER_VELOCITY_TOLERANCE_RPM = 50.0;

    // -- Turret (mechanisms/turret/SingleAxisTurret.java) --
    public static double TURRET_MIN_ANGLE_DEG = 0.0;
    public static double TURRET_MAX_ANGLE_DEG = 300.0;
    public static double TURRET_ANGLE_TOLERANCE_DEG = 2.0;

    // -- Intake (mechanisms/intake/RollerIntake.java) --
    public static double INTAKE_POWER = 1.0;

    // -- Intake velocity PID (mechanisms/intake/RollerIntake.java) --
    // Field shape follows FTCLib's Motor#setVeloCoefficients(kP, kI, kD) signature
    // (refract-suite/ftc-shared-foundation/references/library-docs/ftclib/hardware-wrappers/motors.md,
    // "Velocity control" section) rather than a single PIDCoefficients object, since that's the
    // actual call site these three fields feed on every loop.
    public static double INTAKE_VELOCITY_KP = 0.05;
    public static double INTAKE_VELOCITY_KI = 0.0;
    public static double INTAKE_VELOCITY_KD = 0.0;
}
