// Generated by the ftc-construct suite skill (util-audit-dashboard run).
// Adaptation of refract-suite/ftc-shared-foundation/quickstart-template/TeamCode/src/main/java/
// org/firstinspires/ftc/teamcode/mechanisms/intake/RollerIntake.java -- switches the roller from
// open-loop RawPower to closed-loop VelocityControl with a live-tunable PID, and pushes the
// measured velocity to FTC Dashboard as its own graphable telemetry key every loop.
package org.firstinspires.ftc.teamcode.mechanisms.intake;

import com.acmerobotics.dashboard.FtcDashboard;
import com.acmerobotics.dashboard.telemetry.TelemetryPacket;

import com.arcrobotics.ftclib.command.SubsystemBase;
import com.arcrobotics.ftclib.hardware.motors.Motor;

import com.qualcomm.robotcore.hardware.HardwareMap;

import org.firstinspires.ftc.teamcode.RobotConstants;

/**
 * Roller-type {@link Intake}: a single motor spun one way to pick up game
 * pieces, the other way to clear a jam. A claw-type intake implements the
 * same interface with intake()/reverse()/stop() mapped to grip/release/
 * neutral instead.
 *
 * Velocity control: runs in FTCLib's {@link Motor.RunMode#VelocityControl}
 * (refract-suite/.../library-docs/ftclib/hardware-wrappers/motors.md,
 * "Velocity control" section) instead of RawPower, so intake speed is closed-
 * loop rather than an open-loop power fraction. The PID gains are re-read from
 * {@link RobotConstants} every {@link #periodic()} call rather than cached
 * once -- FTC Dashboard's own {@code @Config} docs (tuning-widgets.md) warn
 * that a value copied once at construction goes stale and never observes
 * later dashboard edits; re-reading the static fields each loop is the fix
 * the same doc recommends.
 *
 * Dashboard graph: the FTC Dashboard telemetry-api.md docs describe two ways
 * data reaches the dashboard -- a shared {@code Telemetry} (addData/update,
 * which is what {@code RobotTelemetry.wrap} already fans out to both DS and
 * dashboard), or a raw {@link TelemetryPacket} dispatched directly via
 * {@code FtcDashboard#sendTelemetryPacket()}. This class uses the second form:
 * subsystems in this template have no {@code Telemetry} reference threaded
 * into them (only {@code TeamOpMode} does), and sending an independent packet
 * avoids interleaving with whatever the OpMode's own
 * {@code telemetry.update()} call buffers elsewhere in the same loop (a
 * caveat telemetry-api.md calls out explicitly: "this indirection can mask
 * the presence of multiple sendTelemetryPacket() calls in a single loop
 * iteration"). Any numeric key put on a packet shows up as its own graphable
 * line in the dashboard's Graph view automatically -- no separate
 * registration step beyond the key name.
 */
public class RollerIntake extends SubsystemBase implements Intake {

    private Motor roller;

    @Override
    public void init(HardwareMap hardwareMap) {
        roller = new Motor(hardwareMap, "intake");
        roller.setRunMode(Motor.RunMode.VelocityControl);
    }

    @Override
    public void intake() {
        roller.set(RobotConstants.INTAKE_POWER);
    }

    @Override
    public void reverse() {
        roller.set(-RobotConstants.INTAKE_POWER);
    }

    @Override
    public void stop() {
        roller.stopMotor();
    }

    /**
     * FTCLib's CommandScheduler calls every registered subsystem's periodic()
     * once per loop (driven by {@code TeamOpMode.run()}'s {@code super.run()}).
     * Re-reads the tunable PID gains live and reports the measured velocity as
     * its own dashboard graph line -- ponytail: no smoothing/filtering on the
     * reported value, add if the raw encoder-rate graph is too noisy to tune
     * against.
     */
    @Override
    public void periodic() {
        roller.setVeloCoefficients(
                RobotConstants.INTAKE_VELOCITY_KP,
                RobotConstants.INTAKE_VELOCITY_KI,
                RobotConstants.INTAKE_VELOCITY_KD);

        TelemetryPacket packet = new TelemetryPacket();
        packet.put("Intake Velocity (ticks/s)", roller.getCorrectedVelocity());
        FtcDashboard.getInstance().sendTelemetryPacket(packet);
    }
}
