/*
 * Generated by ftc-construct (refract-suite quickstart-template lineage).
 * Lineage marker: mirrors _meta.suite_generated_code: true in team-config.yaml --
 * a future corpus-mining pass must not mistake this file for an independently
 * authored data point confirming any pattern this suite itself recommended.
 *
 * Adapted directly from the quickstart-template's shipped FlywheelShooter example
 * (config's season_mechanisms.shooter == flywheel matches it exactly -- step 2's
 * "adapt directly" branch, not a rewrite). No corpus pattern in
 * .claude/skills/ftc-corpus-builder/references/patterns/*.yaml was cited here:
 * the flywheel-shooter patterns that exist there (12808, 16093, 15083, 19043,
 * 24089) all gate on fields this team's config doesn't declare (shooter.aiming,
 * shooter.aiming_stance, season.has_variable_distance_scoring) -- their
 * applicable_when can't be evaluated true or false from what's confirmed, so
 * per the abstention rule they are not cited rather than assumed to match.
 */
package org.firstinspires.ftc.teamcode.mechanisms.shooter;

import com.arcrobotics.ftclib.command.SubsystemBase;
import com.arcrobotics.ftclib.hardware.motors.Motor;

import com.qualcomm.robotcore.hardware.HardwareMap;

import org.firstinspires.ftc.teamcode.RobotConstants;

/**
 * Single-flywheel {@link Shooter}, built on FTCLib's {@link Motor} in
 * {@link Motor.RunMode#VelocityControl}.
 *
 * PID/feedforward coefficients are FTCLib's defaults here. known-failure-modes.md
 * flags "PID instability" as its own root cause -- constants tuned for one
 * robot state don't survive mechanical changes -- so expect to call
 * {@code flywheel.setVeloCoefficients(...)} / {@code setFeedforwardCoefficients(...)}
 * once you have a real flywheel to tune against; don't ship untuned defaults
 * to competition.
 *
 * Hardware map name below ("shooter") must match the Driver Station's Robot
 * Configuration exactly -- update it to your actual config entry.
 */
public class FlywheelShooter extends SubsystemBase implements Shooter {

    private Motor flywheel;
    private double targetRpm = 0.0;

    @Override
    public void init(HardwareMap hardwareMap) {
        flywheel = new Motor(hardwareMap, "shooter");
        flywheel.setRunMode(Motor.RunMode.VelocityControl);
    }

    @Override
    public void setTargetVelocity(double rpm) {
        targetRpm = rpm;
        flywheel.set(rpm / flywheel.getMaxRPM());
    }

    @Override
    public double getCurrentVelocity() {
        // encoder rate is in ticks/sec; convert to RPM via counts-per-revolution
        return flywheel.getRate() * 60.0 / flywheel.getCPR();
    }

    @Override
    public boolean atTargetVelocity() {
        return Math.abs(getCurrentVelocity() - targetRpm) <= RobotConstants.SHOOTER_VELOCITY_TOLERANCE_RPM;
    }

    @Override
    public void stop() {
        targetRpm = 0.0;
        flywheel.stopMotor();
    }
}
