package org.firstinspires.ftc.teamcode.drivetrain;

// Generated by ftc-construct (refract suite). Phase D RoadRunner regression-retest fixture run
// (veteran-roadrunner-confirmed.yaml). See _meta.suite_generated_code convention in
// team-config.yaml — this header is that same lineage marker for a generated source file.

import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.HardwareMap;

/**
 * Config-selected drivetrain implementation for software_stack.opmode_style ==
 * raw_linear_opmode: joystick driving goes straight to {@link DcMotor}, no FTCLib
 * drivebase helper. Implements the suite's existing {@link Drivetrain} interface
 * (refract-suite/ftc-shared-foundation/quickstart-template/.../drivetrain/Drivetrain.java)
 * unchanged — that interface is framework-agnostic (init/drive/stop only), so it
 * applies here exactly as it does to the FTCLib-based MecanumDrivetrain example.
 *
 * Nothing in this class is RoadRunner-specific. Mecanum wheel-power mixing is
 * standard four-wheel kinematics (robot-centric strafe/forward/turn -> four wheel
 * powers, normalized to [-1, 1]), not a value or API pulled from any library doc --
 * grounding obligations here are limited to the raw SDK calls, which come from
 * ftc-sdk/opmode-basics.md's own worked example:
 *   `motorTest = hardwareMap.get(DcMotor.class, "motorTest");` (opmode-basics.md line 67)
 * and ftc-sdk/hardware-configuration.md's confirmation that hardwareMap.get(...) is
 * the standard device-retrieval call (hardware-configuration.md lines 34-69).
 *
 * Motor names below must match the Driver Station's Robot Configuration exactly --
 * update them (or make them constructor parameters) to match your actual config.
 */
public class RawMecanumDrivetrain implements Drivetrain {

    private DcMotor frontLeft, frontRight, backLeft, backRight;

    @Override
    public void init(HardwareMap hardwareMap) {
        frontLeft = hardwareMap.get(DcMotor.class, "front_left");
        frontRight = hardwareMap.get(DcMotor.class, "front_right");
        backLeft = hardwareMap.get(DcMotor.class, "back_left");
        backRight = hardwareMap.get(DcMotor.class, "back_right");

        frontLeft.setDirection(DcMotor.Direction.REVERSE);
        backLeft.setDirection(DcMotor.Direction.REVERSE);

        frontLeft.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        frontRight.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        backLeft.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        backRight.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
    }

    @Override
    public void drive(double strafe, double forward, double turn) {
        double fl = forward + strafe + turn;
        double fr = forward - strafe - turn;
        double bl = forward - strafe + turn;
        double br = forward + strafe - turn;

        double max = Math.max(1.0, Math.max(Math.abs(fl), Math.max(Math.abs(fr),
                Math.max(Math.abs(bl), Math.abs(br)))));

        frontLeft.setPower(fl / max);
        frontRight.setPower(fr / max);
        backLeft.setPower(bl / max);
        backRight.setPower(br / max);
    }

    @Override
    public void stop() {
        if (frontLeft == null) {
            return;
        }
        frontLeft.setPower(0);
        frontRight.setPower(0);
        backLeft.setPower(0);
        backRight.setPower(0);
    }
}
