/*
 * Generated by ftc-construct (refract-suite quickstart-template lineage).
 * Lineage marker: mirrors _meta.suite_generated_code: true in team-config.yaml.
 * Adapted directly from the quickstart-template's shipped RollerIntake example
 * (config's season_mechanisms.intake == roller matches it exactly).
 */
package org.firstinspires.ftc.teamcode.mechanisms.intake;

import com.arcrobotics.ftclib.command.SubsystemBase;
import com.arcrobotics.ftclib.hardware.motors.Motor;

import com.qualcomm.robotcore.hardware.HardwareMap;

import org.firstinspires.ftc.teamcode.RobotConstants;

/**
 * Roller-type {@link Intake}: a single motor spun one way to pick up game
 * pieces, the other way to clear a jam. A claw-type intake implements the
 * same interface with intake()/reverse()/stop() mapped to grip/release/
 * neutral instead.
 *
 * Hardware map name below ("intake") must match the Driver Station's Robot
 * Configuration exactly -- update it to your actual config entry.
 */
public class RollerIntake extends SubsystemBase implements Intake {

    private Motor roller;

    @Override
    public void init(HardwareMap hardwareMap) {
        roller = new Motor(hardwareMap, "intake");
    }

    @Override
    public void intake() {
        roller.set(RobotConstants.INTAKE_POWER);
    }

    @Override
    public void reverse() {
        roller.set(-RobotConstants.INTAKE_POWER);
    }

    @Override
    public void stop() {
        roller.stopMotor();
    }
}
