package org.firstinspires.ftc.teamcode.opmodes;

// Generated by the ftc-construct skill (refract-suite). Config:
// veteran-roadrunner-confirmed.yaml -- software_stack.pathing = roadrunner,
// software_stack.opmode_style = raw_linear_opmode, drivetrain.type = mecanum.
//
// GROUNDING NOTE -- read this before trusting the heading-read call below:
//
// The requested behavior (driver-relative heading correction via RoadRunner's
// localizer) requires a public API that reads the drive's current heading
// estimate during teleop. That API is NOT GROUNDED -- neither
// refract-suite/ftc-shared-foundation/references/library-docs/roadrunner/core-concepts.md
// nor trajectories.md exposes one. core-concepts.md's only pose-related content
// is the internal `HolonomicController.compute(targetPose, actualPose,
// actualVelActual)` math used DURING trajectory following (project/path.get/
// reparam), not a general "read the localizer's current pose" call for use
// outside a trajectory. tuning.md lists the supported localization hardware
// options (drive encoders, dead wheels, Pinpoint, OTOS) but never names a
// method to read the resulting pose estimate. No mention anywhere in the
// fetched docs of `drive.pose`, `drive.localizer`, `updatePoseEstimate()`, or
// any similarly-named accessor.
//
// Per ftc-construct's ask-don't-guess rule (SKILL.md's standing-principles
// reference), this is shipped as a fail-safe placeholder with a TODO rather
// than a confidently-invented method name -- same treatment as the goBILDA
// build-guide gap documented in SKILL.md step 3. `readHeadingRadians()` below
// is a local stub isolating the one ungrounded call; replace its body with
// whatever your installed MecanumDrive.java actually exposes (commonly a
// `drive.pose.heading` field or `drive.updatePoseEstimate()` call in the real
// quickstart source, per the RoadRunner GitHub project -- but that specific
// shape was not present in the fetched docs, so it is not cited here as
// grounded).

import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;

import org.firstinspires.ftc.teamcode.MecanumDrive;

/**
 * Field-centric TeleOp: rotates driver-stick input by the robot's current
 * heading (read from RoadRunner's localizer -- see the TODO in
 * {@link #readHeadingRadians}) so forward on the stick is always away from the
 * driver, regardless of which way the robot is currently facing.
 *
 * Motor hardware names below must match the Driver Station's Robot
 * Configuration -- same placeholder convention as the template's other
 * example OpModes.
 */
@TeleOp(name = "RoadRunner Field-Centric TeleOp", group = "Template")
public class RoadRunnerFieldCentricTeleOp extends LinearOpMode {

    private DcMotorEx frontLeft, frontRight, backLeft, backRight;
    private MecanumDrive drive;

    @Override
    public void runOpMode() {
        frontLeft = hardwareMap.get(DcMotorEx.class, "front_left");
        frontRight = hardwareMap.get(DcMotorEx.class, "front_right");
        backLeft = hardwareMap.get(DcMotorEx.class, "back_left");
        backRight = hardwareMap.get(DcMotorEx.class, "back_right");

        frontLeft.setDirection(DcMotor.Direction.REVERSE);
        backLeft.setDirection(DcMotor.Direction.REVERSE);

        // Constructor signature NOT GROUNDED -- see RoadRunnerAutoOpMode's header
        // note; same caveat applies here.
        drive = new MecanumDrive(hardwareMap, new com.acmerobotics.roadrunner.Pose2d(0, 0, 0));

        waitForStart();

        while (opModeIsActive()) {
            double y = -gamepad1.left_stick_y;
            double x = gamepad1.left_stick_x;
            double turn = gamepad1.right_stick_x;

            double heading = readHeadingRadians();

            // Standard field-centric rotation: rotate the driver's (x, y) stick
            // vector by -heading so it's expressed in the robot's own frame
            // before mixing into wheel powers. This math is generic mecanum
            // kinematics, not a RoadRunner-specific API -- no citation needed
            // for the rotation itself, only for where `heading` comes from.
            double rotX = x * Math.cos(-heading) - y * Math.sin(-heading);
            double rotY = x * Math.sin(-heading) + y * Math.cos(-heading);

            double denom = Math.max(Math.abs(rotY) + Math.abs(rotX) + Math.abs(turn), 1.0);
            frontLeft.setPower((rotY + rotX + turn) / denom);
            backLeft.setPower((rotY - rotX + turn) / denom);
            frontRight.setPower((rotY - rotX - turn) / denom);
            backRight.setPower((rotY + rotX - turn) / denom);

            telemetry.addData("heading (rad)", heading);
            telemetry.update();
        }
    }

    /**
     * NOT GROUNDED -- see the class-level comment. Isolates the one ungrounded
     * call to a single place rather than scattering an invented method name
     * through the drive loop above. TODO: replace with whatever accessor your
     * installed MecanumDrive.java actually exposes for the current pose
     * estimate before running this on a robot.
     */
    private double readHeadingRadians() {
        throw new UnsupportedOperationException(
                "TODO: wire this to MecanumDrive's actual pose/localizer accessor -- "
                        + "not present in the fetched RoadRunner docs, see class header.");
    }
}
