package org.firstinspires.ftc.teamcode.opmodes;

// Generated by the ftc-construct skill (refract-suite). Config:
// veteran-roadrunner-confirmed.yaml -- software_stack.pathing = roadrunner,
// software_stack.opmode_style = raw_linear_opmode, drivetrain.type = mecanum.
//
// GROUNDING NOTES (read before trusting any call below without checking the
// citation list in the generation report):
//
// - MecanumDrive: the class name itself is confirmed by
//   refract-suite/ftc-shared-foundation/references/library-docs/roadrunner/tuning.md
//   ("Pick `MecanumDrive` or `TankDrive` and set the correct hardware names.").
//   installation.md step 4 explains this class isn't a library class you import --
//   it's one of the quickstart's own copied source files
//   (org.firstinspires.ftc.teamcode.MecanumDrive), so no import statement below.
// - Trajectory building methods (.setTangent, .splineTo, .lineToX, .lineToY,
//   .splineToConstantHeading, .splineToLinearHeading, .splineToSplineHeading) are
//   grounded verbatim in trajectories.md's "Building trajectories" section.
// - Action composition (Actions.runBlocking, SequentialAction) is grounded in
//   trajectories.md's "Actions -- the core execution unit" section.
// - PARTIALLY GROUNDED: the import package (com.acmerobotics.roadrunner.*) is
//   not spelled out verbatim anywhere in the fetched docs -- no import
//   statement appears in any code sample. It's inferred from two things that
//   ARE in the docs: installation.md's Maven coordinates
//   ("com.acmerobotics.roadrunner:core:1.0.1", ":actions:1.0.1") and
//   core-concepts.md's module-layout description ("`core` -- the foundational
//   math/planning module ... `actions` -- builds on core; adds the Action
//   execution model"). The class names (Pose2d, Vector2d, SequentialAction,
//   Actions) are grounded by their exact appearance in code samples; the dotted
//   package path they're imported from is an inference, not a quoted line.
// - NOT GROUNDED: trajectories.md documents the builder METHODS ("these are the
//   builder methods used to construct a Trajectory / TrajectoryActionBuilder
//   chain") but never shows (a) the entry-point call that obtains a
//   TrajectoryActionBuilder from a MecanumDrive instance, or (b) the terminal
//   call that turns a finished chain into a runnable Action. Neither
//   `drive.actionBuilder(pose)` nor `.build()` appears anywhere in
//   trajectories.md or core-concepts.md. The two calls below are marked
//   NOT GROUNDED at the point they're used -- verify both against the actual
//   MecanumDrive.java shipped by the quickstart in this project before running,
//   per ftc-construct's ask-don't-guess rule (this is a corpus-completeness
//   gap, not a wiring one -- same class of gap as the goBILDA build-guide
//   exception documented in SKILL.md).

import com.acmerobotics.roadrunner.Pose2d;
import com.acmerobotics.roadrunner.Vector2d;
import com.acmerobotics.roadrunner.SequentialAction;
import com.acmerobotics.roadrunner.Actions;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

import org.firstinspires.ftc.teamcode.MecanumDrive;

/**
 * Autonomous OpMode: follows one RoadRunner trajectory from a start pose to a
 * scoring pose, then a second trajectory back to a parking pose.
 *
 * Placeholder field coordinates (inches, radians) -- adjust to your real field
 * geometry before competition, same convention as the template's other
 * placeholder poses/presets.
 */
@Autonomous(name = "RoadRunner Auto", group = "Template")
public class RoadRunnerAutoOpMode extends LinearOpMode {

    @Override
    public void runOpMode() {
        Pose2d startPose = new Pose2d(0, 0, 0);

        // MecanumDrive(HardwareMap, Pose2d) constructor signature is NOT shown in
        // the fetched docs either -- tuning.md only says to "pick MecanumDrive ...
        // and set the correct hardware names," it doesn't give the constructor.
        // This call assumes the quickstart's stock constructor shape; verify
        // against the actual MecanumDrive.java in this project.
        MecanumDrive drive = new MecanumDrive(hardwareMap, startPose);

        // NOT GROUNDED: .actionBuilder(...) as the entry point is not shown in
        // trajectories.md/core-concepts.md. Left in place as the placeholder
        // convention pending verification (see header note above).
        var toScorePath = drive.actionBuilder(startPose)
                .setTangent(0)
                // grounded: trajectories.md "Position primitives" -- .splineTo(new
                // Vector2d(48, 48), Math.PI / 2)
                .splineTo(new Vector2d(24, 36), Math.PI / 2)
                // grounded: trajectories.md "Heading primitives" -- constant heading
                .splineToConstantHeading(new Vector2d(24, 48), Math.PI / 2)
                .build(); // NOT GROUNDED -- see header note

        var parkPath = drive.actionBuilder(new Pose2d(24, 48, Math.PI / 2))
                // grounded: trajectories.md "Position primitives" -- .lineToY(36)
                .lineToY(36)
                .build(); // NOT GROUNDED -- see header note

        waitForStart();
        if (isStopRequested()) return;

        // grounded: trajectories.md "Actions -- the core execution unit" --
        // Actions.runBlocking(new SequentialAction(...)) composes and drives a
        // sequence of Action objects to completion.
        Actions.runBlocking(new SequentialAction(
                toScorePath,
                parkPath
        ));

        telemetry.addData("status", "auto complete");
        telemetry.update();
    }
}
