package org.firstinspires.ftc.teamcode.opmodes;

// Generated by ftc-construct (refract suite). Phase D RoadRunner regression-retest fixture run
// (veteran-roadrunner-confirmed.yaml, software_stack.pathing == roadrunner,
// software_stack.opmode_style == raw_linear_opmode). See _meta.suite_generated_code convention
// in team-config.yaml -- this header is that same lineage marker for a generated source file.

import com.acmerobotics.roadrunner.Action;
import com.acmerobotics.roadrunner.Pose2d;
import com.acmerobotics.roadrunner.Vector2d;
import com.acmerobotics.roadrunner.ftc.Actions;
import com.acmerobotics.roadrunner.ftc.MecanumDrive;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

/**
 * Autonomous OpMode: build a RoadRunner trajectory and follow it.
 *
 * opmode_style == raw_linear_opmode (core-feature-model.yaml line 62), so this extends
 * {@link LinearOpMode} directly per the SDK's own worked structure
 * (ftc-sdk/opmode-basics.md lines 28-56: `@TeleOp`/`@Autonomous` class extends
 * `LinearOpMode`, implements `runOpMode()`, calls `waitForStart()`). This deliberately
 * does NOT go through the template's TeamOpMode/CommandOpMode base -- that base is
 * FTCLib CommandScheduler scaffolding, which is the OTHER opmode_style
 * (ftclib_command_based), not the one this config confirmed.
 *
 * === RoadRunner grounding, call by call ===
 *
 * `MecanumDrive` construction (below): the class itself is NOT invented here. It is
 * the drive class the RoadRunner docs say you obtain by copying the quickstart
 * project's `teamcode` source into your own project --
 * "Step 4 -- copy quickstart source files. Download the quickstart project from
 * GitHub and copy everything under its `teamcode` folder ... into your project's
 * TeamCode/src/main/java/org/firstinspires/ftc/teamcode." (installation.md lines
 * 61-64). No constructor signature or field/method list for MecanumDrive is given in
 * any of the four fetched RoadRunner doc files (core-concepts.md, trajectories.md,
 * installation.md, tuning.md) -- tuning.md only says "Pick MecanumDrive or TankDrive
 * and set the correct hardware names" (tuning.md line 15). The constructor call below
 * (`new MecanumDrive(hardwareMap, startPose)`) is the external quickstart file's own
 * public constructor, not something re-derived from the fetched-doc corpus; a team
 * wiring this up needs the actual copied-in MecanumDrive.java present in their
 * project for this line to compile. Flagging this distinction plainly rather than
 * presenting it as doc-verified the same way the builder-chain calls below are.
 *
 * Trajectory-builder chain methods used below ARE each directly grounded in
 * trajectories.md's "Building trajectories" section:
 *   - `.splineTo(new Vector2d(x, y), heading)`  -- trajectories.md line 110-111
 *   - `.splineToConstantHeading(...)`            -- trajectories.md lines 124-127
 *   - `.setTangent(0)`                           -- trajectories.md line 121 / 126
 *   - `Actions.runBlocking(...)`                 -- trajectories.md line 33
 *
 * The actual builder ENTRY POINT (`drive.actionBuilder(startPose)`) is likewise part
 * of the external MecanumDrive quickstart class per installation.md's copy-in
 * instruction above, not a method whose name/signature is spelled out in the fetched
 * doc text -- same caveat as the constructor.
 */
@Autonomous(name = "Auto: Follow Trajectory (RoadRunner)", group = "Template")
public class AutoFollowTrajectory extends LinearOpMode {

    @Override
    public void runOpMode() {
        Pose2d startPose = new Pose2d(0, 0, 0);

        // MecanumDrive: external quickstart class, copied into the project per
        // installation.md step 4 -- see class javadoc above for the grounding caveat.
        MecanumDrive drive = new MecanumDrive(hardwareMap, startPose);

        // Builder chain: every method call in this chain is grounded in
        // trajectories.md (see class javadoc). Field distances below are placeholders
        // -- a real run needs real field coordinates, not invented by this generation.
        Action trajectory = drive.actionBuilder(startPose)
                .splineTo(new Vector2d(30, 30), Math.PI / 2)          // trajectories.md line 110-111
                .setTangent(0)                                          // trajectories.md line 121/126
                .splineToConstantHeading(new Vector2d(48, 48), 0)      // trajectories.md line 124-127
                .build();

        telemetry.addData("status", "initialized");
        telemetry.update();

        waitForStart(); // ftc-sdk/opmode-basics.md line 70: "All linear op modes should have
                         // a waitForStart statement..."

        if (opModeIsActive()) {
            // Actions.runBlocking: trajectories.md line 33. Interruptible despite the
            // name (trajectories.md line 34), so STOP still works mid-trajectory.
            Actions.runBlocking(trajectory);
        }
    }
}
