package org.firstinspires.ftc.teamcode.opmodes;

// Generated by ftc-construct (refract suite). Phase D RoadRunner regression-retest fixture run
// (veteran-roadrunner-confirmed.yaml). See _meta.suite_generated_code convention in
// team-config.yaml -- this header is that same lineage marker for a generated source file.

import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

import org.firstinspires.ftc.teamcode.drivetrain.Drivetrain;
import org.firstinspires.ftc.teamcode.drivetrain.RawMecanumDrivetrain;

/**
 * TeleOp: driver-relative (field-centric) drive with heading correction sourced from
 * RoadRunner's localizer.
 *
 * opmode_style == raw_linear_opmode (core-feature-model.yaml line 62) -- plain
 * LinearOpMode per ftc-sdk/opmode-basics.md's worked example (lines 28-56), same as
 * {@link AutoFollowTrajectory}. Joystick input and wheel-power output are plain SDK
 * calls through {@link RawMecanumDrivetrain} (no RoadRunner dependency there).
 *
 * === The RoadRunner-specific piece: current-heading read for driver-relative control ===
 *
 * Field-centric driving needs the robot's CURRENT heading (not the target heading
 * used mid-trajectory in auto) to rotate the joystick vector into field coordinates
 * every teleop loop. The user asked for this to come from "RoadRunner's localizer."
 *
 * This is exactly the corpus gap Phase B found and standing-principles.md section 10
 * already names verbatim: "a library-docs utilization test reported 'partially
 * grounded' on RoadRunner -- explicitly named a real gap (the teleop localizer/
 * pose-read API absent from the fetched docs)" (references/standing-principles.md
 * lines 195-198). Re-checked directly against all four fetched RoadRunner doc files
 * for this generation (core-concepts.md, trajectories.md, installation.md, tuning.md)
 * and the gap is still there:
 *   - core-concepts.md's HolonomicController.compute(targetPose, actualPose,
 *     actualVelActual) (lines 71-76) takes an `actualPose` parameter, which confirms
 *     RoadRunner tracks a live pose internally during path-following -- but the doc
 *     never shows how a caller (e.g. a TeleOp loop, outside path-following) reads
 *     that pose back out. No `drive.pose`, `drive.localizer`, `updatePoseEstimate()`,
 *     or equivalent public accessor appears anywhere in the four files.
 *   - tuning.md lists supported localization *hardware* options (drive encoders, two/
 *     three dead wheels, Pinpoint, SparkFun OTOS -- tuning.md lines 23-27) but never
 *     the software call that reads localizer output back into teleop code.
 *   - The elite-team pattern corpus's own closest example (16093-C,
 *     .claude/skills/ftc-corpus-builder/references/patterns/16093.yaml lines 80-106)
 *     independently confirms the same shape from real competition code: that team's
 *     RoadRunner localizer usage is a hand-written Pinpoint-hardware adapter
 *     (overriding getWheelPositions/getRawExternalHeading/etc.), not a stock documented
 *     pose-read call -- and its `applicable_when` requires `sensing.odometry ==
 *     goBILDA_pinpoint`, which this config does not have (config has `dead_wheels`),
 *     so it isn't even citable here as an applicable pattern. Also per that pattern's
 *     own notes: "RR's autonomous-following API ... has ZERO live opmode callers --
 *     RR is live ONLY for the localizer abstraction + teleop telemetry" in that team's
 *     code, i.e. even the teams actually shipping this don't get it from a documented
 *     stock API either.
 *
 * Per standing-principles.md section 2 (abstention) and the SKILL.md's own goBILDA-gap
 * precedent ("Treat a miss here as an ask-don't-guess abstention ... ship a fail-safe
 * placeholder with a TODO"), the correct move is NOT to invent a plausible-looking
 * call like `drive.pose.heading` -- that would be exactly the "wrong guess that
 * compiles" standing-principles.md section 4 warns against. Instead: stub it,
 * fail safe (falls back to robot-centric driving, never an unbounded/uncontrolled
 * correction), and leave a TODO naming the exact missing artifact.
 */
@TeleOp(name = "TeleOp: Driver-Relative (RoadRunner localizer)", group = "Template")
public class TeleOpDriverRelative extends LinearOpMode {

    private Drivetrain drivetrain;

    @Override
    public void runOpMode() {
        drivetrain = new RawMecanumDrivetrain();
        drivetrain.init(hardwareMap);

        telemetry.addData("status", "initialized");
        telemetry.update();

        waitForStart();

        while (opModeIsActive()) {
            double strafe = gamepad1.left_stick_x;
            double forward = -gamepad1.left_stick_y; // ftc-sdk/opmode-basics.md line 99: negate Y
            double turn = gamepad1.right_stick_x;

            double headingRad = readRoadRunnerHeadingRad();

            double cos = Math.cos(-headingRad);
            double sin = Math.sin(-headingRad);
            double fieldStrafe = strafe * cos - forward * sin;
            double fieldForward = strafe * sin + forward * cos;

            drivetrain.drive(fieldStrafe, fieldForward, turn);

            telemetry.addData("heading (rad, RoadRunner localizer)", headingRad);
            telemetry.addData("heading source", headingRad == 0.0
                    ? "STUBBED -- see readRoadRunnerHeadingRad() TODO" : "live");
            telemetry.update();
        }

        drivetrain.stop();
    }

    /**
     * STUB -- not grounded, deliberately not fabricated.
     *
     * TODO(roadrunner-localizer-gap): none of the four fetched RoadRunner doc files
     * (core-concepts.md, trajectories.md, installation.md, tuning.md) document a
     * public pose-read / localizer-query API usable outside a running trajectory
     * (see class javadoc above for the full grounding trail). Filling this in for
     * real needs one of:
     *   (a) a fresh fetch of RoadRunner's actual MecanumDrive.java source (the file
     *       installation.md says to copy from the quickstart repo) to find its real
     *       public pose field/accessor, or
     *   (b) an explicit answer from the team on which localizer-read call their
     *       copied-in MecanumDrive actually exposes, since this axis
     *       (sensing.odometry == dead_wheels) is a supported RoadRunner localization
     *       option per tuning.md lines 23-27 but the accessor is undocumented here.
     *
     * Fail-safe default: returns 0.0 (no field-centric rotation applied -- driving
     * degrades to robot-centric, never an uncontrolled/undefined correction) rather
     * than guessing a call that might not compile or might silently read the wrong
     * value.
     */
    private double readRoadRunnerHeadingRad() {
        // ponytail: stub with a named ceiling, not a guess -- see TODO above for the
        // exact missing artifact and how to close it.
        return 0.0;
    }
}
