// Generated by ftc-construct (Refract suite). See _meta.suite_generated_code in team-config.yaml.
// Target path once applied: TeamCode/src/main/java/org/firstinspires/ftc/teamcode/vision/GameElementPipeline.java
//
// Grounded against:
//   refract-suite/ftc-shared-foundation/references/library-docs/easyopencv/pipeline-api.md
//     - pipelines extend OpenCvPipeline and implement processFrame(Mat)
//     - auxiliary Mats are instance fields, not locals, to avoid leaking native memory (.release())
//     - results are cached to an instance field and read via a getter, never returned mid-pipeline
// Config grounding: sensing.vision = webcam_easyopencv (team-config.yaml) -> EasyOpenCV, not Limelight/VisionPortal.
//
// ponytail: single-color HSV threshold + largest-contour centroid. No multi-object tracking,
// no shape classification. Add those when the game element set actually needs disambiguating
// more than one color/blob at a time.

package org.firstinspires.ftc.teamcode.vision;

import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfPoint;
import org.opencv.core.Point;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.imgproc.Imgproc;
import org.openftc.easyopencv.OpenCvPipeline;

import java.util.ArrayList;
import java.util.List;

/**
 * Detects a single colored game element in the webcam frame via HSV thresholding
 * + largest-contour centroid, per EasyOpenCV's pipeline-api.md pattern.
 *
 * Thresholds are constructor args, not a hardware-catalog value or dashboard tunable
 * (this request only asked for the detection pipeline) -- tune per-color at construction.
 */
public class GameElementPipeline extends OpenCvPipeline {

    // Instance Mats, reused every frame -- pipeline-api.md's leak-avoidance rule.
    private final Mat hsv = new Mat();
    private final Mat mask = new Mat();
    private final Mat hierarchy = new Mat();

    private final Scalar lowerBound;
    private final Scalar upperBound;
    private final double minAreaPx;

    // Latest result, written by processFrame(), read by the owning subsystem's getters.
    private volatile boolean found = false;
    private volatile double centerX = 0;
    private volatile double centerY = 0;
    private volatile double areaPx = 0;

    /**
     * @param lowerBound HSV lower threshold (H: 0-179, S/V: 0-255)
     * @param upperBound HSV upper threshold
     * @param minAreaPx  contours smaller than this (in pixels^2) are treated as noise, not a detection
     */
    public GameElementPipeline(Scalar lowerBound, Scalar upperBound, double minAreaPx) {
        this.lowerBound = lowerBound;
        this.upperBound = upperBound;
        this.minAreaPx = minAreaPx;
    }

    @Override
    public Mat processFrame(Mat input) {
        Imgproc.cvtColor(input, hsv, Imgproc.COLOR_RGB2HSV);
        Core.inRange(hsv, lowerBound, upperBound, mask);

        List<MatOfPoint> contours = new ArrayList<>();
        Imgproc.findContours(mask, contours, hierarchy, Imgproc.RETR_EXTERNAL, Imgproc.CHAIN_APPROX_SIMPLE);

        MatOfPoint largest = null;
        double largestArea = 0;
        for (MatOfPoint c : contours) {
            double area = Imgproc.contourArea(c);
            if (area > largestArea) {
                largestArea = area;
                largest = c;
            }
        }

        if (largest != null && largestArea >= minAreaPx) {
            Rect bounds = Imgproc.boundingRect(largest);
            found = true;
            areaPx = largestArea;
            centerX = bounds.x + bounds.width / 2.0;
            centerY = bounds.y + bounds.height / 2.0;

            Imgproc.rectangle(input, bounds, new Scalar(0, 255, 0), 3);
            Imgproc.circle(input, new Point(centerX, centerY), 6, new Scalar(255, 0, 0), -1);
        } else {
            found = false;
        }

        return input;
    }

    public boolean isDetected() {
        return found;
    }

    /** Frame-pixel X of the detected element's bounding-box center; only valid when isDetected(). */
    public double getCenterX() {
        return centerX;
    }

    /** Frame-pixel Y of the detected element's bounding-box center; only valid when isDetected(). */
    public double getCenterY() {
        return centerY;
    }

    public double getAreaPx() {
        return areaPx;
    }
}
