// Generated by ftc-construct (Refract suite). See _meta.suite_generated_code in team-config.yaml.
// Target path once applied: TeamCode/src/main/java/org/firstinspires/ftc/teamcode/vision/GameElementVision.java
//
// Grounded against:
//   refract-suite/ftc-shared-foundation/references/library-docs/easyopencv/camera-api.md
//     - OpenCvWebcam obtained via hardwareMap.get(WebcamName.class, ...) + OpenCvCameraFactory.createWebcam(...)
//     - open asynchronously, start streaming only from the onOpened() callback
//     - camera.setPipeline(pipeline) attaches the vision pipeline
// Config grounding: sensing.vision = webcam_easyopencv (team-config.yaml) -- no VisionPortal/Limelight calls here.
// Structural rule (SKILL.md step 4): all hardwareMap/camera access stays inside this owning class;
// OpModes only call init()/getPipeline().

package org.firstinspires.ftc.teamcode.vision;

import com.qualcomm.robotcore.hardware.HardwareMap;

import org.firstinspires.ftc.robotcore.external.hardware.camera.WebcamName;
import org.openftc.easyopencv.OpenCvCamera;
import org.openftc.easyopencv.OpenCvCameraFactory;
import org.openftc.easyopencv.OpenCvCameraRotation;
import org.openftc.easyopencv.OpenCvWebcam;

/**
 * Owns the webcam + {@link GameElementPipeline}. Per camera-api.md, the camera is opened
 * asynchronously and streaming only starts from the onOpened() callback.
 *
 * ponytail: fixed 640x480 stream and UPRIGHT orientation (typical external-webcam mount).
 * Add a constructor param for resolution/rotation if a mount ever needs sideways orientation.
 */
public class GameElementVision {

    private static final int STREAM_WIDTH = 640;
    private static final int STREAM_HEIGHT = 480;

    private OpenCvWebcam webcam;
    private final GameElementPipeline pipeline;

    public GameElementVision(GameElementPipeline pipeline) {
        this.pipeline = pipeline;
    }

    /** Acquire the webcam from the hardware map and start streaming with the pipeline attached. */
    public void init(HardwareMap hardwareMap, String webcamConfigName) {
        int cameraMonitorViewId = hardwareMap.appContext.getResources()
                .getIdentifier("cameraMonitorViewId", "id", hardwareMap.appContext.getPackageName());
        WebcamName webcamName = hardwareMap.get(WebcamName.class, webcamConfigName);
        webcam = OpenCvCameraFactory.getInstance().createWebcam(webcamName, cameraMonitorViewId);

        webcam.setPipeline(pipeline);
        webcam.openCameraDeviceAsync(new OpenCvCamera.AsyncCameraOpenListener() {
            @Override
            public void onOpened() {
                webcam.startStreaming(STREAM_WIDTH, STREAM_HEIGHT, OpenCvCameraRotation.UPRIGHT);
            }

            @Override
            public void onError(int errorCode) {
                // ponytail: no retry/backoff -- surface via telemetry in the OpMode loop
                // (isDetected() will simply stay false, which is a safe default).
            }
        });
    }

    public GameElementPipeline getPipeline() {
        return pipeline;
    }
}
