package org.firstinspires.ftc.teamcode.opmodes;

// Generated by the ftc-construct skill (refract-suite). See
// refract-suite/ftc-shared-foundation/references/library-docs/pedro-pathing/
// {path-building.md, examples.md} for the Follower/PathBuilder API calls used
// below -- cited call-by-call in the generation report, not recalled from
// memory. Config: veteran-swerve-turret.yaml, software_stack.pathing = pedro_pathing,
// software_stack.opmode_style = ftclib_command_based, season_mechanisms.intake = roller.
//
// NOTE: this file only covers the auto routine's path-follow + intake logic
// requested. It assumes org.firstinspires.ftc.teamcode.pedroPathing.Constants
// (Pedro's own generated FollowerConstants/createFollower file, produced by the
// separate Pedro Pathing tuning/quickstart install, not by this suite's
// mechanism template) already exists in the team's real project -- every Pedro
// Pathing example OpMode in path-building.md/examples.md calls
// Constants.createFollower(hardwareMap) rather than constructing a Follower
// inline, so that convention is followed here rather than guessed.

import com.arcrobotics.ftclib.command.CommandOpMode;

import com.pedropathing.follower.Follower;
import com.pedropathing.geometry.BezierCurve;
import com.pedropathing.geometry.Pose;
import com.pedropathing.paths.PathChain;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;

import org.firstinspires.ftc.teamcode.mechanisms.intake.Intake;
import org.firstinspires.ftc.teamcode.mechanisms.intake.RollerIntake;
import org.firstinspires.ftc.teamcode.pedroPathing.Constants;

/**
 * Autonomous OpMode: follows a single 3-point Bezier path (start, control,
 * end pose), holds the final point, and runs the roller intake once the
 * follower has settled there.
 *
 * This extends {@link CommandOpMode} (not {@code TeamOpMode}) directly because
 * TeamOpMode's {@code onRun()} hook is a per-loop callback -- the same shape
 * this OpMode needs to drive {@code follower.update()} and the path-state
 * check every loop, without adding a second competing abstraction on top of
 * TeamOpMode for a single auto routine. Adjust poses to real field
 * coordinates before competition -- the values below are placeholders, same
 * convention as ExampleTeleOp's placeholder RPM/angle presets.
 */
@Autonomous(name = "Three Point Auto", group = "Template")
public class ThreePointAutoOpMode extends CommandOpMode {

    // Placeholder field poses (inches, radians) -- Pedro's coordinate system,
    // see references/library-docs/pedro-pathing/path-building.md "Coordinates".
    private final Pose startPose = new Pose(20, 20, 0);
    private final Pose controlPose = new Pose(40, 40, 0);
    private final Pose endPose = new Pose(60, 20, Math.toRadians(90));

    private Follower follower;
    private PathChain threePointPath;
    private Intake intake;

    // FSM state: 0 = following path (holding end), 1 = intake running, -1 = done.
    private int pathState;

    @Override
    public void initialize() {
        follower = Constants.createFollower(hardwareMap);
        follower.setStartingPose(startPose);

        threePointPath = follower.pathBuilder()
                .addPath(new BezierCurve(startPose, controlPose, endPose))
                .setLinearHeadingInterpolation(startPose.getHeading(), endPose.getHeading())
                .build();

        intake = new RollerIntake();
        intake.init(hardwareMap);

        pathState = 0;
    }

    @Override
    public void run() {
        super.run(); // drives the FTCLib CommandScheduler
        follower.update();

        switch (pathState) {
            case 0:
                // Kick off the 3-point path. holdEnd=true tells the follower to
                // keep correcting to endPose after the path completes, rather
                // than releasing control -- this is what "holds the final
                // point" means for Pedro's Follower.
                follower.followPath(threePointPath, true);
                pathState = 1;
                break;

            case 1:
                // !follower.isBusy() becomes true once the follower has both
                // finished the path and settled within its end constraints.
                if (!follower.isBusy()) {
                    intake.intake();
                    pathState = 2;
                }
                break;

            case 2:
                // Follower keeps holding endPose (holdEnd=true, set above) while
                // the intake keeps running; nothing else to advance here.
                break;
        }

        telemetry.addData("path state", pathState);
        telemetry.addData("x", follower.getPose().getX());
        telemetry.addData("y", follower.getPose().getY());
        telemetry.addData("heading", follower.getPose().getHeading());
        telemetry.update();
    }
}
