// Generated by ftc-construct (Refract suite). See _meta.suite_generated_code in team-config.yaml.
// NOT a full file -- one-line addition to the existing onRun() in:
//   TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/ExampleTeleOp.java
//
// Grounded against ftc-dashboard/telemetry-api.md: a numeric telemetry.addData() key reaching
// FTC Dashboard's Telemetry is what the dashboard's graph panel picks up as a selectable,
// real-time-graphable field -- no separate widget/graph class is needed. TeamOpMode already
// wraps `telemetry` with RobotTelemetry.wrap() (MultipleTelemetry to DS + dashboard) for every
// OpMode, so this line is the entire "expose it on the dashboard graph" step.

    @Override
    protected void onRun() {
        telemetry.addData("shooter rpm", shooter.getCurrentVelocity());
        telemetry.addData("shooter at target", shooter.atTargetVelocity());
        telemetry.addData("turret angle", turret.getCurrentAngle());
        telemetry.addData("intake velocity (ticks/s)", ((RollerIntake) intake).getVelocityTicksPerSec()); // NEW
        // telemetry.update() is called for us by TeamOpMode.run() -- no need to call it here.
    }
