// Generated by ftc-construct (Refract suite). See _meta.suite_generated_code in team-config.yaml.
// This is the FULL updated file -- target path once applied:
//   TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotConstants.java
// Only the "Intake velocity PID" block below is new; everything else is the existing
// template file, unchanged (this class is a template-inherited @Config domain --
// SKILL.md step 3 says adapting the existing pattern needs no fresh read, only the
// new addition below needed one).
//
// Grounded against:
//   refract-suite/ftc-shared-foundation/references/library-docs/ftc-dashboard/tuning-widgets.md
//     - static, non-final fields on an @Config-annotated class are live-editable from the dashboard
//   refract-suite/ftc-shared-foundation/references/library-docs/ftclib/hardware-wrappers/motors.md
//     - Motor.RunMode.VelocityControl + setVeloCoefficients(kP, kI, kD) is FTCLib's built-in
//       velocity PID surface -- reused instead of hand-rolling a PIDFController.

package org.firstinspires.ftc.teamcode;

import com.acmerobotics.dashboard.config.Config;

/**
 * Live-tunable constants, following the FTC Dashboard {@code @Config} idiom
 * carried over from FTCLib-Quickstart's own {@code DriveConstants.java}.
 *
 * IMPORTANT -- read before adding a field here: known-failure-modes.md's
 * "global mutable static state" entry documents a real failure class where a
 * team wrote to a public static field from OpMode/subsystem lifecycle code at
 * runtime. Static fields outlive a single OpMode run (they live on the app
 * process), so a write during run N silently leaks into run N+1 -- and
 * because it only manifests when run N+1 FOLLOWS run N with the wrong prior
 * value, it passes clean in any single tuning run and shows up as "the robot
 * behaved differently in match 2 for no reason." @Config does not protect
 * against this; it only lets the DASHBOARD write these fields between runs.
 *
 * The rule this class exists under: FTC Dashboard may write these fields
 * (that's what @Config is for). OpMode and subsystem code may only READ them.
 * If a value needs to change during a run, make it an instance field on the
 * subsystem that owns it, not a static here.
 */
@Config
public class RobotConstants {

    // -- Shooter (mechanisms/shooter/FlywheelShooter.java) --
    public static double SHOOTER_VELOCITY_TOLERANCE_RPM = 50.0;

    // -- Turret (mechanisms/turret/SingleAxisTurret.java) --
    public static double TURRET_MIN_ANGLE_DEG = 0.0;
    public static double TURRET_MAX_ANGLE_DEG = 300.0;
    public static double TURRET_ANGLE_TOLERANCE_DEG = 2.0;

    // -- Intake (mechanisms/intake/RollerIntake.java) --
    public static double INTAKE_POWER = 1.0;

    // -- Intake velocity PID (NEW -- mechanisms/intake/RollerIntake.java velocity control) --
    // Starting values are placeholders, not a catalog spec -- these are tuned live via the
    // dashboard, per tuning-widgets.md; there is no "correct" PID gain to look up.
    public static double INTAKE_VELOCITY_KP = 0.05;
    public static double INTAKE_VELOCITY_KI = 0.0;
    public static double INTAKE_VELOCITY_KD = 0.0;
}
