// Generated by ftc-construct (Refract suite). See _meta.suite_generated_code in team-config.yaml.
// This is the FULL updated file -- target path once applied:
//   TeamCode/src/main/java/org/firstinspires/ftc/teamcode/mechanisms/intake/RollerIntake.java
//
// Change from the existing template file: intake()/reverse() now drive the roller through
// FTCLib's Motor.RunMode.VelocityControl instead of RawPower, using the new
// RobotConstants.INTAKE_VELOCITY_K{P,I,D} dashboard-tunable gains, and expose
// getVelocityTicksPerSec() so the OpMode loop can graph it on FTC Dashboard.
//
// Grounded against:
//   refract-suite/ftc-shared-foundation/references/library-docs/ftclib/hardware-wrappers/motors.md
//     - setRunMode(VelocityControl) + setVeloCoefficients(kP, kI, kD); m_motor.set(...) is then a
//       velocity setpoint in [-1, 1] of max ticks/sec, not a raw power fraction
//     - getCorrectedVelocity() -- FTCLib's overflow-corrected reading, preferred over raw getVelocity()
//   refract-suite/ftc-shared-foundation/references/library-docs/ftc-dashboard/telemetry-api.md
//     - a numeric telemetry.addData() key reaching the dashboard's Telemetry (already wired for every
//       OpMode via RobotTelemetry.wrap) is what makes a value graphable -- @Config alone would not.
//       This class exposes the reading; the OpMode's loop (see ExampleTeleOp_intake_graph_snippet.java
//       in this same output folder) does the addData() call that makes it show up as a graph.

package org.firstinspires.ftc.teamcode.mechanisms.intake;

import com.arcrobotics.ftclib.command.SubsystemBase;
import com.arcrobotics.ftclib.hardware.motors.Motor;

import com.qualcomm.robotcore.hardware.HardwareMap;

import org.firstinspires.ftc.teamcode.RobotConstants;

/**
 * Roller-type {@link Intake}: a single motor spun one way to pick up game
 * pieces, the other way to clear a jam. A claw-type intake implements the
 * same interface with intake()/reverse()/stop() mapped to grip/release/
 * neutral instead.
 *
 * Velocity-controlled per RobotConstants.INTAKE_VELOCITY_K{P,I,D} (live-tunable via
 * FTC Dashboard); gains are re-read from RobotConstants on every intake()/reverse() call
 * rather than cached at init(), so a dashboard edit takes effect on the next loop --
 * same "read the static, don't cache a copy" discipline RobotConstants's own class
 * comment already documents for @Config fields.
 */
public class RollerIntake extends SubsystemBase implements Intake {

    private Motor roller;

    @Override
    public void init(HardwareMap hardwareMap) {
        roller = new Motor(hardwareMap, "intake");
        roller.setRunMode(Motor.RunMode.VelocityControl);
        applyVeloCoefficients();
    }

    private void applyVeloCoefficients() {
        roller.setVeloCoefficients(
                RobotConstants.INTAKE_VELOCITY_KP,
                RobotConstants.INTAKE_VELOCITY_KI,
                RobotConstants.INTAKE_VELOCITY_KD);
    }

    @Override
    public void intake() {
        applyVeloCoefficients();
        roller.set(RobotConstants.INTAKE_POWER);
    }

    @Override
    public void reverse() {
        applyVeloCoefficients();
        roller.set(-RobotConstants.INTAKE_POWER);
    }

    @Override
    public void stop() {
        roller.stopMotor();
    }

    /** Corrected velocity in ticks/sec, for the OpMode loop to graph on FTC Dashboard. */
    public double getVelocityTicksPerSec() {
        return roller.getCorrectedVelocity();
    }
}
