// Generated by ftc-construct (refract-suite). Grounded against:
//   refract-suite/ftc-shared-foundation/references/library-docs/rev-robotics/device-configuration-and-expansion-hub.md
// Config: veteran-limelight-easyopencv-confirmed.yaml (control_hardware.expansion_hub_count now 2)
package org.firstinspires.ftc.teamcode;

import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.hardware.Servo;

/**
 * Hardware initialization for devices wired to the second REV Expansion Hub.
 *
 * IMPORTANT naming/addressing convention (see device-naming-explanation.md for the
 * full citation): hardwareMap.get() looks devices up by the unique, case-sensitive
 * NAME each device was given in the Driver Station configuration file -- that name
 * is the only thing this code (or any FTC SDK call) ever references. Which physical
 * hub a device is wired to is NOT part of that name and is NOT part of the
 * hardwareMap lookup -- the SDK does not expose "which hub" as an addressable
 * property to user code. The hub identity only matters at configuration time (RS485
 * port-to-port wiring + the Driver Station config UI, where the second hub shows up
 * as its own portal, e.g. "Expansion Hub 2").
 *
 * Practical convention this team should follow (not an SDK requirement, just
 * hygiene): give devices on the second hub a name that signals which hub they're on
 * -- e.g. a "_hub2" suffix -- purely so a human reading the Driver Station config
 * list or this code can tell at a glance where a device is physically wired. The
 * suffix has no functional meaning to hardwareMap.get(); it is a naming discipline
 * this file adopts, not a REV/FTC-mandated scheme.
 */
public class SecondExpansionHubHardware {

    public DcMotor climbMotor;
    public Servo wristServo;

    public void init(HardwareMap hardwareMap) {
        // Names below must exactly match (case-sensitive) what was typed into the
        // Driver Station config for the port on Expansion Hub 2. The "_hub2" suffix
        // is our own convention for readability -- see class javadoc above.
        climbMotor = hardwareMap.get(DcMotor.class, "climb_hub2");
        wristServo = hardwareMap.get(Servo.class, "wrist_hub2");
    }
}
