package org.firstinspires.ftc.teamcode.vision;

// Generated by ftc-construct (refract-suite). Config: team 99901 (veteran/swerve/turret,
// sensing.vision=limelight_3a confirmed). API usage grounded against
// refract-suite/ftc-shared-foundation/references/library-docs/limelight/java-api.md and
// localization.md — see per-call citations in the generation report. Never edit libs/.

import com.qualcomm.hardware.limelightvision.LLResult;
import com.qualcomm.hardware.limelightvision.Limelight3A;
import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.hardware.IMU;
import org.firstinspires.ftc.robotcore.external.navigation.AngleUnit;
import org.firstinspires.ftc.robotcore.external.navigation.Pose3D;

/**
 * Reads the latest {@link LLResult} from the team's Limelight 3A and derives a field-relative
 * robot pose using MegaTag2. Follows the template convention (see SingleAxisTurret): all
 * hardware access confined to this class, init(HardwareMap) entry point, no telemetry calls
 * here directly -- the owning OpMode pulls getFieldPose() and reports it through
 * RobotTelemetry itself.
 *
 * MT2 requires the robot's current yaw every frame (localization.md: "Unlike MegaTag (MT1),
 * MegaTag2 (MT2) assumes that you know your robot's heading (yaw)."). This class reads yaw
 * from the Control Hub's built-in IMU (standard FTC SDK, not Limelight-specific -- not cited
 * against the Limelight docs).
 */
public class LimelightLocalizer {

    private Limelight3A limelight;
    private IMU imu;

    /**
     * java-api.md, "1. Initialization":
     *   limelight = hardwareMap.get(Limelight3A.class, "limelight");
     *   limelight.setPollRateHz(100);
     *   limelight.start();
     */
    public void init(HardwareMap hardwareMap) {
        limelight = hardwareMap.get(Limelight3A.class, "limelight");
        limelight.setPollRateHz(100);
        limelight.start();

        imu = hardwareMap.get(IMU.class, "imu");
        imu.initialize(new IMU.Parameters(
                new org.firstinspires.ftc.robotcore.external.navigation.RevHubOrientationOnRobot(
                        org.firstinspires.ftc.robotcore.external.navigation.RevHubOrientationOnRobot.LogoFacingDirection.UP,
                        org.firstinspires.ftc.robotcore.external.navigation.RevHubOrientationOnRobot.UsbFacingDirection.FORWARD
                )
        ));
    }

    /**
     * Call once per loop before reading the pose. MT2 requires robot yaw submitted every
     * frame:
     *
     * localization.md, "Robot Localization with MegaTag2":
     *   "Requirements: ... Robot orientation/yaw is submitted every frame (FTC:
     *   limelight.updateRobotOrientation(yawDegrees) ..."
     *
     * java-api.md, "6. Where's My Robot? (MegaTag 2)":
     *   double robotYaw = imu.getAngularOrientation().firstAngle;
     *   limelight.updateRobotOrientation(robotYaw);
     *
     * (java-api.md's own snippet reads yaw via the older getAngularOrientation().firstAngle;
     * this class uses the current FTC SDK IMU.getRobotYawPitchRollAngles().getYaw(), which is
     * the standard SDK replacement -- not a Limelight-specific call, so not cited against the
     * Limelight docs.)
     */
    public void updateOrientation() {
        double robotYawDegrees = imu.getRobotYawPitchRollAngles().getYaw(AngleUnit.DEGREES);
        limelight.updateRobotOrientation(robotYawDegrees);
    }

    /**
     * java-api.md, "3. Getting and Using Results":
     *   LLResult result = limelight.getLatestResult();
     *   if (result != null && result.isValid()) { ... }
     */
    public LLResult getLatestResult() {
        return limelight.getLatestResult();
    }

    /**
     * Field-relative robot pose via MegaTag2.
     *
     * java-api.md, "6. Where's My Robot? (MegaTag 2)":
     *   Pose3D botpose_mt2 = result.getBotpose_MT2();
     *   if (botpose_mt2 != null) {
     *       double x = botpose_mt2.getPosition().x;
     *       double y = botpose_mt2.getPosition().y;
     *   }
     *
     * Call updateOrientation() every loop before this, per localization.md's MT2 requirements
     * list above. Returns null if there's no valid result or no tags in view this frame --
     * callers must not assume a pose is always available (ponytail: no fallback/fusion with
     * goBILDA Pinpoint odometry here -- add that in the drivetrain localizer if the team
     * decides to fuse sources; this class only does what was asked).
     */
    public Pose3D getFieldPoseMT2() {
        LLResult result = getLatestResult();
        if (result == null || !result.isValid()) {
            return null;
        }
        return result.getBotpose_MT2();
    }
}
