// Generated by ftc-construct suite.
// Grounded in: refract-suite/ftc-shared-foundation/references/library-docs/easyopencv/camera-api.md
package org.firstinspires.ftc.teamcode.vision;

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.hardware.HardwareMap;
import org.firstinspires.ftc.robotcore.external.hardware.camera.WebcamName;
import org.openftc.easyopencv.OpenCvCamera;
import org.openftc.easyopencv.OpenCvCameraFactory;
import org.openftc.easyopencv.OpenCvCameraRotation;
import org.openftc.easyopencv.OpenCvWebcam;

/**
 * Minimal webcam + EasyOpenCV wiring for ColorGameElementPipeline.
 *
 * Every camera call here is cited against camera-api.md's numbered program flow:
 *   1. cameraMonitorViewId resolved from hardwareMap.appContext (section 1: live viewport)
 *   2. OpenCvCameraFactory.getInstance().createWebcam(webcamName, viewId) (section 2:
 *      webcam-specific factory method, takes WebcamName + optional view id)
 *   3. camera.openCameraDeviceAsync(...) with onOpened/onError (section 3: recommended
 *      async open, non-blocking)
 *   4. camera.startStreaming(width, height, rotation) inside onOpened (section 4)
 *   5. camera.setPipeline(pipeline) (section 5: pipeline attach, may be called anytime)
 */
@TeleOp(name = "Color Game Element Vision", group = "vision")
public class ColorGameElementVisionOpMode extends LinearOpMode {

    private OpenCvCamera webcam;
    private ColorGameElementPipeline pipeline;

    @Override
    public void runOpMode() {
        HardwareMap hw = hardwareMap;

        int cameraMonitorViewId = hw.appContext.getResources().getIdentifier(
                "cameraMonitorViewId", "id", hw.appContext.getPackageName());

        WebcamName webcamName = hw.get(WebcamName.class, "Webcam 1");

        webcam = OpenCvCameraFactory.getInstance().createWebcam(webcamName, cameraMonitorViewId);
        pipeline = new ColorGameElementPipeline(ColorGameElementPipeline.TargetColor.YELLOW);
        webcam.setPipeline(pipeline);

        webcam.openCameraDeviceAsync(new OpenCvCamera.AsyncCameraOpenListener() {
            @Override
            public void onOpened() {
                // Common supported resolution per camera-api.md section 4.
                webcam.startStreaming(640, 480, OpenCvCameraRotation.UPRIGHT);
            }

            @Override
            public void onError(int errorCode) {
                telemetry.addData("EasyOpenCV", "camera open error: %d", errorCode);
                telemetry.update();
            }
        });

        waitForStart();

        while (opModeIsActive()) {
            telemetry.addData("Detected", pipeline.isDetected());
            telemetry.addData("BoundingBox", pipeline.getLastBoundingBox());
            telemetry.update();
        }
    }
}
