// Generated by ftc-construct suite.
// Grounded in: refract-suite/ftc-shared-foundation/references/library-docs/easyopencv/pipeline-api.md
//              refract-suite/ftc-shared-foundation/references/library-docs/easyopencv/camera-api.md
package org.firstinspires.ftc.teamcode.vision;

import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.imgproc.Imgproc;
import org.openftc.easyopencv.OpenCvPipeline;

/**
 * Detects a colored game element by thresholding in HSV space and finding the
 * largest matching contour's bounding box + centroid.
 *
 * API usage grounded in pipeline-api.md:
 * - extends OpenCvPipeline, implements processFrame(Mat) -> Mat (required)
 * - implements init(Mat firstFrame) for one-time setup Mats (required for submats;
 *   used here to size the working buffers)
 * - auxiliary Mats declared as instance fields, not locals, to avoid leaking native
 *   memory each frame (explicit guidance in pipeline-api.md)
 * - result is cached to an instance field and exposed via a getter, read from the
 *   OpMode thread without blocking the vision thread (pipeline-api.md "Getting data
 *   to the OpMode thread")
 */
public class ColorGameElementPipeline extends OpenCvPipeline {

    public enum TargetColor { RED, BLUE, YELLOW }

    // ponytail: HSV bounds are a starting point for one color family (yellow game
    // element); retune with real field lighting before relying on this at competition.
    private static final Scalar YELLOW_LOWER = new Scalar(20, 100, 100);
    private static final Scalar YELLOW_UPPER = new Scalar(35, 255, 255);

    // Instance Mats, reused every frame per pipeline-api.md guidance (avoids
    // forgetting .release() on locals -> OOME/crash on the Robot Controller app).
    private final Mat hsvMat = new Mat();
    private final Mat thresholdMat = new Mat();
    private final Mat hierarchy = new Mat();

    private volatile Rect lastBoundingBox = null;
    private volatile boolean lastDetectionValid = false;

    private final TargetColor targetColor;

    public ColorGameElementPipeline(TargetColor targetColor) {
        this.targetColor = targetColor;
    }

    @Override
    public void init(Mat firstFrame) {
        // No submats needed for this pipeline; buffers above are sized implicitly
        // by cvtColor/inRange on the first processFrame call.
    }

    @Override
    public Mat processFrame(Mat input) {
        // EasyOpenCV delivers RGBA frames (per easyopencv/setup.md "IMPORTANT NOTE"),
        // not BGR like desktop OpenCV -- convert from RGBA, not BGR.
        Imgproc.cvtColor(input, hsvMat, Imgproc.COLOR_RGB2HSV);

        Scalar lower = YELLOW_LOWER;
        Scalar upper = YELLOW_UPPER;
        Core.inRange(hsvMat, lower, upper, thresholdMat);

        java.util.List<org.opencv.core.MatOfPoint> contours = new java.util.ArrayList<>();
        Imgproc.findContours(thresholdMat, contours, hierarchy,
                Imgproc.RETR_EXTERNAL, Imgproc.CHAIN_APPROX_SIMPLE);

        org.opencv.core.MatOfPoint largest = null;
        double largestArea = 0;
        for (org.opencv.core.MatOfPoint c : contours) {
            double area = Imgproc.contourArea(c);
            if (area > largestArea) {
                largestArea = area;
                largest = c;
            }
        }

        if (largest != null && largestArea > 200) {
            lastBoundingBox = Imgproc.boundingRect(largest);
            lastDetectionValid = true;
            Imgproc.rectangle(input, lastBoundingBox, new Scalar(0, 255, 0), 3);
        } else {
            lastDetectionValid = false;
        }

        // Returned Mat is what's shown on the live preview (pipeline-api.md).
        return input;
    }

    /** Cached result accessor -- no processing cost, per pipeline-api.md pattern. */
    public boolean isDetected() {
        return lastDetectionValid;
    }

    /** Cached result accessor -- no processing cost, per pipeline-api.md pattern. */
    public Rect getLastBoundingBox() {
        return lastBoundingBox;
    }
}
