/*
 * Generated by ftc-construct (refract-suite quickstart-template lineage).
 * Lineage marker: mirrors _meta.suite_generated_code: true in team-config.yaml --
 * a future corpus-mining pass must not mistake this file for an independently
 * authored data point confirming any pattern this suite itself recommended.
 * Unchanged from refract-suite/ftc-shared-foundation/quickstart-template -- copied
 * as-is because this generation added no new per-mechanism runtime-tunable value.
 */
package org.firstinspires.ftc.teamcode;

import com.acmerobotics.dashboard.config.Config;

/**
 * Live-tunable constants, following the FTC Dashboard {@code @Config} idiom
 * carried over from FTCLib-Quickstart's own {@code DriveConstants.java}.
 *
 * IMPORTANT -- read before adding a field here: known-failure-modes.md's
 * "global mutable static state" entry documents a real failure class where a
 * team wrote to a public static field from OpMode/subsystem lifecycle code at
 * runtime. Static fields outlive a single OpMode run (they live on the app
 * process), so a write during run N silently leaks into run N+1 -- and
 * because it only manifests when run N+1 FOLLOWS run N with the wrong prior
 * value, it passes clean in any single tuning run and shows up as "the robot
 * behaved differently in match 2 for no reason." @Config does not protect
 * against this; it only lets the DASHBOARD write these fields between runs.
 *
 * The rule this class exists under: FTC Dashboard may write these fields
 * (that's what @Config is for). OpMode and subsystem code may only READ them.
 * If a value needs to change during a run, make it an instance field on the
 * subsystem that owns it, not a static here.
 */
@Config
public class RobotConstants {

    // -- Shooter (mechanisms/shooter/FlywheelShooter.java) --
    public static double SHOOTER_VELOCITY_TOLERANCE_RPM = 50.0;

    // -- Turret (mechanisms/turret/SingleAxisTurret.java) --
    public static double TURRET_MIN_ANGLE_DEG = 0.0;
    public static double TURRET_MAX_ANGLE_DEG = 300.0;
    public static double TURRET_ANGLE_TOLERANCE_DEG = 2.0;

    // -- Intake (mechanisms/intake/RollerIntake.java) --
    public static double INTAKE_POWER = 1.0;
}
