/*
 * Generated by ftc-construct (refract-suite quickstart-template lineage).
 * Lineage marker: mirrors _meta.suite_generated_code: true in team-config.yaml.
 * Unchanged from refract-suite/ftc-shared-foundation/quickstart-template -- copied
 * as-is; every OpMode this generation writes extends it.
 */
package org.firstinspires.ftc.teamcode.opmodes;

import com.arcrobotics.ftclib.command.CommandOpMode;

import org.firstinspires.ftc.teamcode.telemetry.RobotTelemetry;

/**
 * Base class for every competition OpMode in this template.
 *
 * Two things happen here, once, so no subclass can forget them:
 *
 * 1. Telemetry is wired to both the Driver Station and FTC Dashboard before
 *    {@link #onInit()} runs, and flushed automatically every loop after
 *    {@link #onRun()} runs. Telemetry is default-on, not something a subsystem
 *    or OpMode author opts into.
 * 2. {@code initialize()}/{@code run()} (FTCLib's {@link CommandOpMode} hooks)
 *    are sealed with {@code final} so the scaffolding above cannot be
 *    bypassed by accident. Subclasses hook {@link #onInit()} / {@link #onRun()}
 *    instead -- register subsystems and button bindings in onInit(), let the
 *    FTCLib CommandScheduler (driven by super.run()) do the per-mechanism
 *    work. That's the structural point of this whole template: there is no
 *    method here an author can pile 500 lines of mixed drivetrain/shooter/
 *    turret/intake logic into, because each mechanism already has its own
 *    interface and subsystem class (see the drivetrain/ and mechanisms/
 *    packages). A God-OpMode needs a place to grow; this template doesn't
 *    give it one.
 */
public abstract class TeamOpMode extends CommandOpMode {

    @Override
    public final void initialize() {
        telemetry = RobotTelemetry.wrap(telemetry);
        onInit();
    }

    @Override
    public final void run() {
        super.run(); // drives the FTCLib CommandScheduler: subsystem periodic() + scheduled commands
        onRun();
        telemetry.update(); // flush every loop -- the "not opt-in" part
    }

    /**
     * Build hardware/subsystems and wire gamepad button bindings here. This
     * runs once, before {@code waitForStart()}. Subsystems extending FTCLib's
     * {@code SubsystemBase} (see drivetrain/ and mechanisms/) register
     * themselves with the CommandScheduler in their own constructor -- no
     * separate registration call needed.
     */
    protected abstract void onInit();

    /**
     * Optional per-loop hook for anything that isn't naturally expressed as a
     * scheduled Command (e.g. driver-relative telemetry readouts). Most
     * OpModes won't need to override this -- the scheduler already drives
     * subsystem periodic() and commands via super.run().
     */
    protected void onRun() {
        // no-op by default
    }
}
