/*
 * Generated by ftc-construct (refract-suite quickstart-template lineage).
 * Lineage marker: mirrors _meta.suite_generated_code: true in team-config.yaml --
 * a future corpus-mining pass must not mistake this file for an independently
 * authored data point confirming any pattern this suite itself recommended.
 *
 * NEW file (step 2's "no template example" branch): the quickstart-template only
 * ships a MecanumDrivetrain example. This team's confirmed config
 * (drivetrain.type: swerve, module_count: 4, module_source: custom_fabricated,
 * software_stack.pathing: pedro_pathing) has no matching template example, so
 * this class is written fresh against Pedro Pathing's own documented swerve
 * setup API -- grounded in
 * refract-suite/ftc-shared-foundation/references/library-docs/pedro-pathing/swerve.md
 * ("Swerve Constants Example" section), not recalled from memory.
 */
package org.firstinspires.ftc.teamcode.drivetrain;

import com.pedropathing.control.FilteredPIDFCoefficients;
import com.pedropathing.control.PIDFCoefficients;
import com.pedropathing.follower.Follower;
import com.pedropathing.follower.FollowerConstants;
import com.pedropathing.ftc.FollowerBuilder;
import com.pedropathing.ftc.drivetrains.CoaxialPod;
import com.pedropathing.ftc.drivetrains.SwerveConstants;
import com.pedropathing.geometry.Pose;
import com.pedropathing.paths.PathConstraints;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.HardwareMap;

/**
 * Pod wiring + Follower construction for this team's 4-module coaxial swerve
 * drivetrain, via Pedro Pathing's {@code SwerveConstants}/{@code CoaxialPod} API.
 *
 * <p><b>Every numeric constant below is a PLACEHOLDER</b> copied from Pedro
 * Pathing's own published swerve-constants example robot, not a value measured
 * on this team's chassis -- module_source is {@code custom_fabricated}, so
 * there is no catalog spec to read these from the way
 * ftc-hardware-lookup would for an off-the-shelf part. swerve.md's own tuning
 * section is explicit that pod PIDF gains, analog-encoder min/max voltages,
 * angle offsets, and the {@code dtLength}/{@code dtWidth} lateral offsets are
 * only obtainable by running the Pedro {@code Tuning} OpMode's swerve section
 * (Analog Min/Max Tuner, LocalizationTest, Swerve Offsets Test, Swerve Turn
 * Test) against the real, built 4-module chassis -- the same "don't ship
 * untuned defaults to competition" rule
 * {@link org.firstinspires.ftc.teamcode.mechanisms.shooter.FlywheelShooter}
 * already carries for its own PID. Hardware map names
 * ("front_left_drive"/"front_left_steer"/"front_left_encoder", etc.) must
 * match the Driver Station's Robot Configuration exactly.
 */
public final class PedroSwerveConstants {

    private PedroSwerveConstants() {
        // static utility -- not instantiable
    }

    // PLACEHOLDER (Pedro's example robot, not this team's) -- retune via
    // swerve.md's "Pod PIDF Tuning" section.
    private static final double POD_KP = 0.0055 * 180 / Math.PI;
    private static final double POD_KD = 0.00015 * 180 / Math.PI;
    private static final double POD_KF_FRONT = 0.0130;
    private static final double POD_KF_BACK = 0.0190;

    // PLACEHOLDER -- measure this team's actual chassis footprint (half-length /
    // half-width between opposite pods, in the units Pose uses elsewhere in
    // this project) per swerve.md's "Lateral Offsets" section.
    private static final double DT_LENGTH = 271.148;
    private static final double DT_WIDTH = 270.7;

    public static FollowerConstants followerConstants = new FollowerConstants()
            .forwardZeroPowerAcceleration(-197.1) // PLACEHOLDER -- retune (ForwardZeroPowerAccelerationTuner)
            .lateralZeroPowerAcceleration(-197.1) // swerve: lateral == forward, same tuner (swerve.md tip #1)
            .useSecondaryDrivePIDF(true).useSecondaryHeadingPIDF(true)
            .useSecondaryTranslationalPIDF(true)

            .translationalPIDFCoefficients(new PIDFCoefficients(0.125, 0, 0.008, 0))
            .secondaryTranslationalPIDFCoefficients(new PIDFCoefficients(0.0825, 0, 0.008, 0))

            .headingPIDFCoefficients(new PIDFCoefficients(1.75, 0, 0.003, 0))
            .secondaryHeadingPIDFCoefficients(new PIDFCoefficients(0.8, 0, 0.015, 0))

            .drivePIDFCoefficients(new FilteredPIDFCoefficients(0.005, 0, 0.00003, 0.6, 0.13))
            .secondaryDrivePIDFCoefficients(
                    new FilteredPIDFCoefficients(0.004, 0, 0.000002, 0.6, 0.13))

            // PLACEHOLDER -- weigh the actual robot; do not ship the example robot's mass.
            .mass(13.732);

    public static SwerveConstants swerveConstants = new SwerveConstants()
            .velocity(73.9) // PLACEHOLDER -- max linear velocity, retune per swerve.md
            .useBrakeModeInTeleOp(true);

    private static CoaxialPod frontLeft(HardwareMap hardwareMap) {
        CoaxialPod pod = new CoaxialPod(
                hardwareMap,
                "front_left_drive",
                "front_left_steer",
                "front_left_encoder",
                new PIDFCoefficients(POD_KP, 0, POD_KD, POD_KF_FRONT),
                DcMotorSimple.Direction.REVERSE, // PLACEHOLDER -- confirm via "Motor Directions" tuning step
                DcMotorSimple.Direction.REVERSE, // PLACEHOLDER -- confirm via "Encoder Directions" tuning step
                Math.toRadians(353.1), // PLACEHOLDER angle offset -- retune (Angle Offset Tuning)
                new Pose(DT_LENGTH, DT_WIDTH),
                0.025, 3.290, // PLACEHOLDER analog min/max volts -- retune (Analog Min/Max Tuner)
                false
        );
        pod.setMotorCachingThreshold(0.05);
        pod.setServoCachingThreshold(0.05);
        return pod;
    }

    private static CoaxialPod frontRight(HardwareMap hardwareMap) {
        CoaxialPod pod = new CoaxialPod(
                hardwareMap,
                "front_right_drive",
                "front_right_steer",
                "front_right_encoder",
                new PIDFCoefficients(POD_KP, 0, POD_KD, POD_KF_FRONT),
                DcMotorSimple.Direction.FORWARD, // PLACEHOLDER -- confirm via tuning
                DcMotorSimple.Direction.REVERSE, // PLACEHOLDER -- confirm via tuning
                Math.toRadians(348.2), // PLACEHOLDER angle offset -- retune
                new Pose(DT_LENGTH, -DT_WIDTH),
                0.018, 3.288, // PLACEHOLDER analog min/max volts -- retune
                false
        );
        pod.setMotorCachingThreshold(0.05);
        pod.setServoCachingThreshold(0.05);
        return pod;
    }

    private static CoaxialPod backLeft(HardwareMap hardwareMap) {
        CoaxialPod pod = new CoaxialPod(
                hardwareMap,
                "back_left_drive",
                "back_left_steer",
                "back_left_encoder",
                new PIDFCoefficients(POD_KP, 0, POD_KD, POD_KF_BACK),
                DcMotorSimple.Direction.REVERSE, // PLACEHOLDER -- confirm via tuning
                DcMotorSimple.Direction.REVERSE, // PLACEHOLDER -- confirm via tuning
                Math.toRadians(179.3), // PLACEHOLDER angle offset -- retune
                new Pose(-DT_LENGTH, DT_WIDTH),
                0.029, 3.307, // PLACEHOLDER analog min/max volts -- retune
                false
        );
        pod.setMotorCachingThreshold(0.05);
        pod.setServoCachingThreshold(0.05);
        return pod;
    }

    private static CoaxialPod backRight(HardwareMap hardwareMap) {
        CoaxialPod pod = new CoaxialPod(
                hardwareMap,
                "back_right_drive",
                "back_right_steer",
                "back_right_encoder",
                new PIDFCoefficients(POD_KP, 0, POD_KD, POD_KF_BACK),
                DcMotorSimple.Direction.FORWARD, // PLACEHOLDER -- confirm via tuning
                DcMotorSimple.Direction.REVERSE, // PLACEHOLDER -- confirm via tuning
                Math.toRadians(289.5), // PLACEHOLDER angle offset -- retune
                new Pose(-DT_LENGTH, -DT_WIDTH),
                0.014, 3.301, // PLACEHOLDER analog min/max volts -- retune
                false
        );
        pod.setMotorCachingThreshold(0.05);
        pod.setServoCachingThreshold(0.05);
        return pod;
    }

    // PLACEHOLDER path constraints (Pedro's example) -- fine to leave as a
    // starting point, but revisit once auto paths exist for this robot.
    public static PathConstraints pathConstraints =
            new PathConstraints(0.9, 2, 2, 0.03, 50, 1, 10, 1);

    public static Follower createFollower(HardwareMap hardwareMap) {
        return new FollowerBuilder(followerConstants, hardwareMap)
                .pathConstraints(pathConstraints)
                .swerveDrivetrain(swerveConstants,
                        frontLeft(hardwareMap),
                        frontRight(hardwareMap),
                        backLeft(hardwareMap),
                        backRight(hardwareMap))
                .build();
    }
}
